In [ ]:
import numpy as np
import torch

In [ ]:
inp = torch.randint(low=-5, high=6, size=(4, 10))
inp

tensor([[-2, -5,  4, -5,  0,  0, -3, -5, -5, -4],
        [ 3, -1,  0, -4, -4,  5,  1, -3,  0, -3],
        [ 4,  2, -2, -2,  5, -1,  1, -1,  1,  5],
        [-4,  0,  5, -3, -3,  0, -1,  1, -5, -3]])

In [ ]:
x = inp.unsqueeze(2).repeat(1, 1, 10)
x

tensor([[[-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
         [-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
         [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
         [-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
         [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
         [-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
         [-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
         [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4]],

        [[ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
         [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
         [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
         [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
         [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
         [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
         [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
         [-3, -3, -3, -3, -3,

In [ ]:
max_val, _ = torch.max(inp, dim=1, keepdim=True)
stable_inp = inp - max_val
stable_inp_exp = torch.exp(stable_inp)
log_sum_exp = torch.log(torch.sum(stable_inp_exp, dim=1, keepdim=True))
log_softmax = stable_inp - log_sum_exp

log_softmax

tensor([[ -6.04004,  -9.04004,  -0.04004,  -9.04004,  -4.04004,  -4.04004,
          -7.04004,  -9.04004,  -9.04004,  -8.04004],
        [ -2.15745,  -6.15745,  -5.15745,  -9.15745,  -9.15745,  -0.15745,
          -4.15745,  -8.15745,  -5.15745,  -8.15745],
        [ -1.90060,  -3.90060,  -7.90060,  -7.90060,  -0.90060,  -6.90060,
          -4.90060,  -6.90060,  -4.90060,  -0.90060],
        [ -9.03483,  -5.03483,  -0.03483,  -8.03483,  -8.03483,  -5.03483,
          -6.03483,  -4.03483, -10.03483,  -8.03483]])

In [ ]:
log_softmax = torch.randint(low=-10, high=0, size=(4, 10))
log_softmax

tensor([[ -9,  -4,  -1,  -9,  -1,  -1,  -9, -10, -10, -10],
        [ -8,  -4,  -3,  -1,  -6,  -9,  -8,  -9, -10,  -3],
        [ -9,  -6,  -1,  -3,  -6,  -1,  -9, -10,  -1,  -5],
        [ -4,  -1,  -5,  -3, -10,  -6, -10,  -2,  -3,  -9]])

In [ ]:
grad_out = (torch.empty(4, 10).uniform_(-5, 5))
grad_out

tensor([[-2.5606, -1.4689,  2.2906, -4.4380,  4.6103, -4.9157, -2.1490, -4.6109,
         -3.2578, -1.0215],
        [-4.2503,  4.4206,  0.8344, -4.8416, -3.8437, -2.9422, -4.0043, -0.0152,
         -2.1762,  1.1747],
        [ 1.4633, -3.7548,  4.8123, -3.6829, -3.4304, -2.3915,  0.5832,  2.0365,
          2.3769, -3.6167],
        [-0.4049,  3.7115, -2.4256,  3.7949, -3.9259, -3.5103, -2.7454, -0.2203,
         -0.7856, -1.3003]])

In [ ]:
grad_out = (torch.empty(4, 10).uniform_(-5, 5)).round().long()
grad_out

tensor([[ 1,  1,  4,  4, -1,  1, -4, -5,  3,  3],
        [ 4,  4, -2, -2, -4, -4,  4,  2, -1, -2],
        [-3, -2,  1, -4, -4, -2,  1, -1,  3, -1],
        [ 2, -3,  4,  0, -4,  1, -5,  2,  2,  4]])

In [ ]:
softmax = torch.exp(log_softmax)
softmax

tensor([[4.0994e-01, 3.7382e-04, 3.7382e-04, 1.3752e-04, 4.0994e-01, 7.5083e-03,
         2.0410e-02, 1.5081e-01, 3.7382e-04, 1.3752e-04],
        [1.9157e-03, 3.5087e-05, 2.8431e-01, 1.0459e-01, 1.9157e-03, 3.8477e-02,
         3.5087e-05, 9.5376e-05, 2.8431e-01, 2.8431e-01],
        [8.0926e-05, 8.0926e-05, 2.1998e-04, 2.1998e-04, 1.6254e-03, 1.2010e-02,
         2.9771e-05, 2.4124e-01, 6.5575e-01, 8.8746e-02],
        [2.1207e-05, 5.7646e-05, 1.5670e-04, 2.1207e-05, 8.5554e-03, 1.7184e-01,
         1.7184e-01, 1.7184e-01, 4.6711e-01, 8.5554e-03]])

In [ ]:
softmax = torch.exp(log_softmax)
torch.set_printoptions(precision=5, sci_mode=False)
softmax

tensor([[    0.00012,     0.01832,     0.36788,     0.00012,     0.36788,
             0.36788,     0.00012,     0.00005,     0.00005,     0.00005],
        [    0.00034,     0.01832,     0.04979,     0.36788,     0.00248,
             0.00012,     0.00034,     0.00012,     0.00005,     0.04979],
        [    0.00012,     0.00248,     0.36788,     0.04979,     0.00248,
             0.36788,     0.00012,     0.00005,     0.36788,     0.00674],
        [    0.01832,     0.36788,     0.00674,     0.04979,     0.00005,
             0.00248,     0.00005,     0.13534,     0.04979,     0.00012]])

In [ ]:
neg_softmax = -softmax
neg_softmax

tensor([[-4.0994e-01, -3.7382e-04, -3.7382e-04, -1.3752e-04, -4.0994e-01,
         -7.5083e-03, -2.0410e-02, -1.5081e-01, -3.7382e-04, -1.3752e-04],
        [-1.9157e-03, -3.5087e-05, -2.8431e-01, -1.0459e-01, -1.9157e-03,
         -3.8477e-02, -3.5087e-05, -9.5376e-05, -2.8431e-01, -2.8431e-01],
        [-8.0926e-05, -8.0926e-05, -2.1998e-04, -2.1998e-04, -1.6254e-03,
         -1.2010e-02, -2.9771e-05, -2.4124e-01, -6.5575e-01, -8.8746e-02],
        [-2.1207e-05, -5.7646e-05, -1.5670e-04, -2.1207e-05, -8.5554e-03,
         -1.7184e-01, -1.7184e-01, -1.7184e-01, -4.6711e-01, -8.5554e-03]])

In [ ]:
neg_softmax = -softmax
neg_softmax

tensor([[    -0.00012,     -0.01832,     -0.36788,     -0.00012,     -0.36788,
             -0.36788,     -0.00012,     -0.00005,     -0.00005,     -0.00005],
        [    -0.00034,     -0.01832,     -0.04979,     -0.36788,     -0.00248,
             -0.00012,     -0.00034,     -0.00012,     -0.00005,     -0.04979],
        [    -0.00012,     -0.00248,     -0.36788,     -0.04979,     -0.00248,
             -0.36788,     -0.00012,     -0.00005,     -0.36788,     -0.00674],
        [    -0.01832,     -0.36788,     -0.00674,     -0.04979,     -0.00005,
             -0.00248,     -0.00005,     -0.13534,     -0.04979,     -0.00012]])

In [ ]:
neg_softmax_matrix = np.repeat(neg_softmax[:, :, np.newaxis], 10, axis=2)
neg_softmax_matrix

tensor([[[-4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01,
          -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01],
         [-3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04,
          -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04],
         [-3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04,
          -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04],
         [-1.3752e-04, -1.3752e-04, -1.3752e-04, -1.3752e-04, -1.3752e-04,
          -1.3752e-04, -1.3752e-04, -1.3752e-04, -1.3752e-04, -1.3752e-04],
         [-4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01,
          -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01],
         [-7.5083e-03, -7.5083e-03, -7.5083e-03, -7.5083e-03, -7.5083e-03,
          -7.5083e-03, -7.5083e-03, -7.5083e-03, -7.5083e-03, -7.5083e-03],
         [-2.0410e-02, -2.0410e-02, -2.0410e-02, -2.0410e-02, -2.0410e-02,
          -2.0410e-

In [ ]:
neg_softmax_matrix = np.repeat(neg_softmax[:, :, np.newaxis], 10, axis=2)
neg_softmax_matrix

tensor([[[    -0.00012,     -0.00012,     -0.00012,     -0.00012,     -0.00012,
              -0.00012,     -0.00012,     -0.00012,     -0.00012,     -0.00012],
         [    -0.01832,     -0.01832,     -0.01832,     -0.01832,     -0.01832,
              -0.01832,     -0.01832,     -0.01832,     -0.01832,     -0.01832],
         [    -0.36788,     -0.36788,     -0.36788,     -0.36788,     -0.36788,
              -0.36788,     -0.36788,     -0.36788,     -0.36788,     -0.36788],
         [    -0.00012,     -0.00012,     -0.00012,     -0.00012,     -0.00012,
              -0.00012,     -0.00012,     -0.00012,     -0.00012,     -0.00012],
         [    -0.36788,     -0.36788,     -0.36788,     -0.36788,     -0.36788,
              -0.36788,     -0.36788,     -0.36788,     -0.36788,     -0.36788],
         [    -0.36788,     -0.36788,     -0.36788,     -0.36788,     -0.36788,
              -0.36788,     -0.36788,     -0.36788,     -0.36788,     -0.36788],
         [    -0.00012,     -0.000

In [ ]:
dL_dlogSM = torch.eye(10) + neg_softmax_matrix
dL_dlogSM

tensor([[[ 5.9006e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01,
          -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01],
         [-3.7382e-04,  9.9963e-01, -3.7382e-04, -3.7382e-04, -3.7382e-04,
          -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04],
         [-3.7382e-04, -3.7382e-04,  9.9963e-01, -3.7382e-04, -3.7382e-04,
          -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04, -3.7382e-04],
         [-1.3752e-04, -1.3752e-04, -1.3752e-04,  9.9986e-01, -1.3752e-04,
          -1.3752e-04, -1.3752e-04, -1.3752e-04, -1.3752e-04, -1.3752e-04],
         [-4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01,  5.9006e-01,
          -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01, -4.0994e-01],
         [-7.5083e-03, -7.5083e-03, -7.5083e-03, -7.5083e-03, -7.5083e-03,
           9.9249e-01, -7.5083e-03, -7.5083e-03, -7.5083e-03, -7.5083e-03],
         [-2.0410e-02, -2.0410e-02, -2.0410e-02, -2.0410e-02, -2.0410e-02,
          -2.0410e-

In [ ]:
dL_dlogSM = torch.eye(10) + neg_softmax_matrix
dL_dlogSM

tensor([[[     0.99988,     -0.00012,     -0.00012,     -0.00012,     -0.00012,
              -0.00012,     -0.00012,     -0.00012,     -0.00012,     -0.00012],
         [    -0.01832,      0.98168,     -0.01832,     -0.01832,     -0.01832,
              -0.01832,     -0.01832,     -0.01832,     -0.01832,     -0.01832],
         [    -0.36788,     -0.36788,      0.63212,     -0.36788,     -0.36788,
              -0.36788,     -0.36788,     -0.36788,     -0.36788,     -0.36788],
         [    -0.00012,     -0.00012,     -0.00012,      0.99988,     -0.00012,
              -0.00012,     -0.00012,     -0.00012,     -0.00012,     -0.00012],
         [    -0.36788,     -0.36788,     -0.36788,     -0.36788,      0.63212,
              -0.36788,     -0.36788,     -0.36788,     -0.36788,     -0.36788],
         [    -0.36788,     -0.36788,     -0.36788,     -0.36788,     -0.36788,
               0.63212,     -0.36788,     -0.36788,     -0.36788,     -0.36788],
         [    -0.00012,     -0.000

In [ ]:
grad_in = np.einsum('ij,ijk->ik', grad_out, dL_dlogSM)
grad_in

array([[-2.6230872 , -1.531358  ,  2.2281485 , -4.5004086 ,  4.547859  ,
        -4.978121  , -2.2114272 , -4.673348  , -3.3202453 , -1.0839684 ],
       [-3.5677378 ,  5.1032166 ,  1.5169775 , -4.159044  , -3.161071  ,
        -2.2596283 , -3.3216631 ,  0.6673657 , -1.493596  ,  1.8573474 ],
       [-0.23145026, -5.4494896 ,  3.1175764 , -5.3776393 , -5.1250796 ,
        -4.0862575 , -1.1114733 ,  0.3417421 ,  0.6821585 , -5.3114204 ],
       [ 1.1197047 ,  5.2360864 , -0.90098095,  5.3195257 , -2.4012337 ,
        -1.9857196 , -1.2208236 ,  1.3043146 ,  0.73902595,  0.22432137]],
      dtype=float32)

In [ ]:
grad_in = np.einsum('ij,ijk->ik', grad_out, dL_dlogSM)
grad_in

array([[-0.49000222, -0.49000222,  2.50999775,  2.50999786, -2.49000225,
        -0.49000225, -5.49000236, -6.49000216,  1.50999769,  1.50999769],
       [ 4.86916817,  4.86916824, -1.13083191, -1.13083186, -3.13083176,
        -3.13083197,  4.86916817,  2.86916819, -0.13083184, -1.13083191],
       [-3.51470804, -2.5147079 ,  0.48529205, -4.51470804, -4.51470785,
        -2.51470795,  0.48529208, -1.51470793,  2.48529205, -1.51470795],
       [ 2.66724685, -2.3327532 ,  4.66724679,  0.6672468 , -3.33275313,
         1.66724677, -4.33275311,  2.66724683,  2.66724684,  4.66724691]])

In [ ]:
import torch

In [ ]:
log_softmax = torch.tensor([[-1.0, -2.0, -3.0],
               [-0.5, -1.5, -2.5]])
log_softmax

tensor([[-1.0000, -2.0000, -3.0000],
        [-0.5000, -1.5000, -2.5000]])

In [ ]:
grad_output = torch.tensor([[0.1, 0.2, 0.3],
               [0.4, 0.5, 0.6]])
grad_output

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

In [ ]:
neg_softmax = -torch.exp(log_softmax)
neg_softmax

tensor([[-0.3679, -0.1353, -0.0498],
        [-0.6065, -0.2231, -0.0821]])

In [ ]:
neg_softmax_matrix = neg_softmax.unsqueeze(2).repeat(1, 1, 3)
neg_softmax_matrix

tensor([[[-0.3679, -0.3679, -0.3679],
         [-0.1353, -0.1353, -0.1353],
         [-0.0498, -0.0498, -0.0498]],

        [[-0.6065, -0.6065, -0.6065],
         [-0.2231, -0.2231, -0.2231],
         [-0.0821, -0.0821, -0.0821]]])

In [ ]:
dL_dlogSM = torch.eye(3) + neg_softmax_matrix
dL_dlogSM

tensor([[[ 0.6321, -0.3679, -0.3679],
         [-0.1353,  0.8647, -0.1353],
         [-0.0498, -0.0498,  0.9502]],

        [[ 0.3935, -0.6065, -0.6065],
         [-0.2231,  0.7769, -0.2231],
         [-0.0821, -0.0821,  0.9179]]])

In [ ]:
grad_input = torch.einsum('ij,ijk->ik', grad_output, dL_dlogSM)
grad_input

tensor([[ 0.0212,  0.1212,  0.2212],
        [-0.0034,  0.0966,  0.1966]])

In [38]:
x = torch.arange(0, 6*10).reshape(6,10)
x

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [50]:
y = torch.randint(size=(6,), low=0, high=5)
y.unsqueeze(0)

tensor([[4, 4, 3, 4, 0, 0]])

In [56]:
x.gather(dim=1, index=y.unsqueeze(1)).to(torch.float)

tensor([[ 4.],
        [14.],
        [23.],
        [34.],
        [40.],
        [50.]])

In [65]:
target = torch.randint(low=0, high=10, size=(6,), dtype=torch.int64)
target

tensor([2, 3, 6, 2, 1, 0])

In [66]:
batch_size, num_classes = 6, 10
grad_input = torch.zeros(size=(batch_size, num_classes))
grad_input

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
grad_input[torch.arange(batch_size), target] = -1.0 / batch_size
grad_input.size

<function Tensor.size>

In [71]:
activations = torch.randn(4, 10, dtype=torch.double, requires_grad=True)
activations

tensor([[ 1.8341,  0.2855,  0.5735, -0.7621,  0.0707,  1.3355, -0.3580, -0.4784,
          1.2055, -0.2404],
        [ 1.6753, -0.2204, -1.4137,  0.6838,  0.5799,  1.0214, -0.5137,  0.2369,
          0.4138, -1.8059],
        [ 0.3671,  0.1987,  0.4019,  1.1884,  1.9147,  0.5533, -1.1827,  1.5385,
          1.0934,  0.0082],
        [ 0.4710,  0.2887,  0.3467, -0.3845,  0.8863,  0.7807, -0.1697, -0.5592,
          0.1669, -2.0335]], dtype=torch.float64, requires_grad=True)